# 基础镜像
FROM anapsix/alpine-java:8_server-jre_unlimited
# 设定时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# 拷贝jar包
COPY gallery-end.jar /app.jar
# 入口
ENTRYPOINT ["java", "-jar", "/app.jar"]